### ISSUE TITLE
metasploit-framework cannot be install in windows10x64

### ISSUE THREAD

**Issue by RussiaVk** [rapid7/metasploit-omnibus#100]
[https://wx4.sinaimg.cn/mw690/00707GTely1g2cg81r2ucj30dr0ar3yz.jpg](url)

**Comment by busterb** [comment]
To see what is happening, you need to create an install log:

https://www.advancedinstaller.com/user-guide/qa-log.html

I recommend you actually try installing this package as an Admin, it is probably hitting a permissions issue under the covers.
