### ISSUE TITLE
installation finished, but no folder or file created

### ISSUE THREAD

**Issue by FluffyDiscord** [rapid7/metasploit-omnibus#102]
## Expected behavior

Installer with create folder and files in it.

## Current behavior

Does absolutely nothing, looks like it installs, but no file found.

### Metasploit version

no idea, cant check

### I installed Metasploit with:

*latest metasploit installer.msi*,
metasploit-framework-5.0.19+20190425193324.git.7.b9e2e14-1rapid7-1-x64.msi
same results

### OS

win 10 x64 enterprise ltsb

### Additional

Selecting any other place to install, than default C:/ also does nothing and once it looks like its installed and I run the installer once again and select change, I see again C:/ path, even when I selected G:/ in installation before.
I am not running any antivirus/anti-malware software or any of that sort.

Any ideas ? also side question: Will virtual linux machine running on windows work fine? if so, can you point me to a working setup guide please?

**Comment by busterb** [comment]
Dup of #96 it looks like, closing.

**Comment by morgs88** [comment]
I've spent the last 3 hours messing around with metasploit on a windows 10 machine, i installed it to C:\metasploit, pointed to the directory but it installed into D:\metasploit-framework. Installed it twice to make sure i didn't mess up, kinda weird!

Cheers

Brett

**Comment by amr-coding** [comment]
The same thing happens to me, after looking closely I found it installed in my D drive.

**Comment by mukesh-610** [comment]
+1. The PATH variable is set to `C:\metasploit-framework\bin`, but the installation is done in `D:\metasploit-framework`.

I'm running Windows 10 Enterprise 2019 LTSC. I have a SSD on C: and a HDD on D: if that helps.

**Comment by VidathDissanayake** [comment]
Any update on this?

**Comment by Gravitom** [comment]
It's 2024 and this bug still exists

**Comment by samar555** [comment]
check all the drive it install to other driver like D F any other check all drive

**Comment by Brentlyw** [comment]
Bug still exists, if you have other drives it will install to highest drive letter available.
