### ISSUE TITLE
Starting msfconsole in a directory that contain spaces gives an error

### ISSUE THREAD

**Issue by DidierA** [rapid7/metasploit-omnibus#134]
if you run 'msfconsole' and the current directory contains spaces in its name, an error is reported:
```
lv426:~ % cd dir\ with\ space 
lv426:~/dir with space % /usr/bin/msfconsole 
/usr/bin/msfconsole: 14: cd: can't cd to /home/didier/dir
```
line 14 of /usr/bin/msfconsole contains `cd $CWD`, it should be `cd "$CWD"`

**Comment by bcoles** [comment]
How did you install Metasploit?

**Comment by DidierA** [comment]
To confirm:
```
% apt info metasploit-framework
Package: metasploit-framework
Version: 6.0.7+20200913102427~1rapid7-1
Priority: extra
Section: misc
Maintainer: Rapid7 Release Engineering <r7_re@rapid7.com>
Installed-Size: 572 MB
Homepage: https://rapid7.com
License: Unspecified
Vendor: Omnibus <omnibus@getchef.com>
Download-Size: 240 MB
APT-Manual-Installed: yes
APT-Sources: http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid/main amd64 Packages
Description: The full stack of metasploit-framework
```

**Comment by cannujBarfu0negjiz** [comment]
README.md

> if you run 'msfconsole' and the current directory contains spaces in its name, an error is reported:
> 
> ```
> lv426:~ % cd dir\ with\ space 
> lv426:~/dir with space % /usr/bin/msfconsole 
> /usr/bin/msfconsole: 14: cd: can't cd to /home/didier/dir
> ```
> 
> line 14 of /usr/bin/msfconsole contains `cd $CWD`, it should be `cd "$CWD"`

**Comment by adfoster-r7** [comment]
Thanks for the error report; this should be fixed by https://github.com/rapid7/metasploit-omnibus/pull/186 - and available by default in a day or so from now when the next automated build is released :+1:
