### ISSUE TITLE
OpenSUSE Tumbleweed - directory /etc/pki/rpm-gpg/ does not exist - Installer fails

### ISSUE THREAD

**Issue by blu-base** [rapid7/metasploit-omnibus#139]
Using the nightly installer on OpenSUSE Tumbleweed seems to fail right now.

## Symptoms

The gpg-key file `/etc/pki/rpm-gpg/RPM-GPG-KEY-Metasploit` was not written and will result in the following output:

```bash
./msfinstall: line 105: /etc/pki/rpm-gpg/RPM-GPG-KEY-Metasploit: No such file or directory
error: /etc/pki/rpm-gpg/RPM-GPG-KEY-Metasploit: import read failed(2).
Retrieving repository 'metasploit' metadata ---------------------------------------------------------------------------------------------------------------------------------------[\]
Looking for gpg key ID 2007B954 in cache /var/cache/zypp/pubkeys.
Repository metasploit does not define additional 'gpgkey=' URLs.
Warning: File 'repomd.xml' from repository 'metasploit' is signed with an unknown key 'CDFB5FA52007B954'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'metasploit' is signed with an unknown key 'CDFB5FA52007B954'. Continue? [yes/no] (no): no
Retrieving repository 'metasploit' metadata ...................................................................................................................................[error]
Repository 'metasploit' is invalid.
[metasploit|http://downloads.metasploit.com/data/releases/metasploit-framework/rpm] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml
 - Can't provide /repodata/repomd.xml

Please check if the URIs defined for this repository are pointing to a valid repository.
Warning: Skipping repository 'metasploit' because of the above error.
Some of the repositories have not been refreshed because of an error.
Loading repository data...
Reading installed packages...
'metasploit-framework' not found in package names. Trying capabilities.
No provider of 'metasploit-framework' found.
```

## Cause

While `/etc/pki/` does exist, the directory `/etc/pki/rpm-gpg` seem to not exist by default (on my machine). 
That's why the command `print_pgp_key > ${GPG_KEY_FILE}`in line 105 of the `install_suse` function will not write a file.

## Workaround
However when I created the `rpm-gpg` directory manually, the installer (or to be precise: zypper)  proceeded without any further complains, since `${GPG_KEY_FILE}` was now successfully written.

## Possible Fix

I don't know whether the missing `rpm-gpg` directory is specific to my machine or if it is specific to my distro.
As of now, i do not know the indented location for external GPG key files on OpenSUSE Tumbleweed. 

Assuming that directory is uncritical, i would change the `install_suse` function to include a check whether the directory exists. And if it does not exist yet: just create it.

This would change respective function in the [config/templates/metasploit-framework-wrappers/msfupdate.erb](https://github.com/rapid7/metasploit-omnibus/blob/master/config/templates/metasploit-framework-wrappers/msfupdate.erb) file from this:

```bash
install_suse() {
  echo "Checking for and installing update.."
  GPG_KEY_FILE=/etc/pki/rpm-gpg/RPM-GPG-KEY-Metasploit
  echo -n "Adding metasploit-framework to your repository list.."

  zypper ar  -f $DOWNLOAD_URI/rpm metasploit
  print_pgp_key > ${GPG_KEY_FILE}
  rpmkeys --import ${GPG_KEY_FILE}
  zypper install -y metasploit-framework
}
```

to this:

```bash
install_suse() {
  echo "Checking for and installing update.."
  GPG_KEY_FILE_DIR=/etc/pki/rpm-gpg
  if [ ! -d $GPG_KEY_FILE_DIR ]; then
    mkdir -p $GPG_KEY_FILE_DIR
  fi

  GPG_KEY_FILE=$GPG_KEY_FILE_DIR/RPM-GPG-KEY-Metasploit
  echo -n "Adding metasploit-framework to your repository list.."

  zypper ar  -f $DOWNLOAD_URI/rpm metasploit
  print_pgp_key > ${GPG_KEY_FILE}
  rpmkeys --import ${GPG_KEY_FILE}
  zypper install -y metasploit-framework
}
```

Do you consider this a reasonable change? If so, i would go ahead and create a PR with this change, unless it is simpler for one of the maintainers to do it yourself.

**Comment by blu-base** [comment]
I just found #130, @Jkpgibson may I ask which version you have used for your contribution?

**Comment by Jkpgibson** [comment]
> I just found #130, @Jkpgibson may I ask which version you have used for your contribution?

Hi, I believe that directory was not default on my system, either. But it had already been created for a different key, so it just worked for me. I neglected to consider that some people may not have that. Thanks for catching it!

**Comment by blu-base** [comment]
#143 has been merged. Hence this issue is solved.
