### ISSUE TITLE
No new packages for quite some time

### ISSUE THREAD

**Issue by VainlyStrain** [rapid7/metasploit-omnibus#141]
(this is a direct copy of [this issue](https://github.com/rapid7/metasploit-framework/issues/14347), but I figured this would be a better place to post it.)

# Summary

## Relevant information

I have observed that I have not received a Metasploit update for quite some time now. This seems odd, since I usually received nightly builds. Therefore, I have looked up the repository for my OS (rpm.metasploit.com), and indeed, the latest version is still 6.0.13.

Is this intended? Has there been a policy switch, or is this a result of a technical error? (that f.i. an automation script gets not executed anymore)

The Debian repository seems affected as well.

Metasploit has been installed via omnibus on a Fedora 32 box.

**Comment by jmartin-r7** [comment]
Fixed with #140, new packages should deploy within 24 hours.
