### ISSUE TITLE
Metasploit Not installed but showing it at its newest version.

### ISSUE THREAD

**Issue by akshatbhatter1** [rapid7/metasploit-omnibus#167]
I had installed metasploit previously and it was working fine. Then due to some reason I uninstalled it using
`sudo rm -rf /opt/metasploit-framework` but now I want to reinstall it.
I am following the steps given on the webpage: https://docs.rapid7.com/metasploit/installing-the-metasploit-framework/ . I am on ubuntu 20.04 LTS. 
I am using the command

`url https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall`

It gives the following output:
`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6034  100  6034    0     0  41328      0 --:--:-- --:--:-- --:--:-- 41328
Switching to root user to update the package
Adding metasploit-framework to your repository list..OK
Updating package cache..OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (6.1.29+20220206112545~1rapid7-1).
0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.`
 I am unable to figure out why is this happening. I tried to run msfconsole but it says command not found.

Notice the line **"metasploit-framework is already the newest version (6.1.29+20220206112545~1rapid7-1)."** in the output.

What should I do now? Please help!

**Comment by bcoles** [comment]
Try: `apt-get --reinstall install metasploit-framework`

**Comment by akshatbhatter1** [comment]
Thanks! It Worked!
