### ISSUE TITLE
can't be more rediclous ............

### ISSUE THREAD

**Issue by hujiujiu** [rapid7/metasploit-omnibus#177]
can't be more rediclous ............

**Comment by bcoles** [comment]
Thank you for the insightful feedback. How should we make omnibus more ridiculous?

**Comment by h00die** [comment]
More red?

**Comment by hujiujiu** [comment]
> Thank you for the insightful feedback. How should we make omnibus more ridiculous?

sorry for making you feeel bad that ................... I meant to justify why msf-latest downloaded but never setup correctly , exactly said the biggest problem belongs to mine , for I'm controlled by someone's trojan and once i install msf , it must disapper in ten seconds (indeed shorter) even keeping origin settings , yes , don't be amazed , I paid sometime on figure out how long It shall gone .............

but ......... so said that after I tryout finding and remove everything of that virus .......... msf still seems hate my computer ..........

even if next time I gussessd that msf has gone after some wrong console-cmd reply .......... open that installer *.msi , he just shown that msf is still there and belive in it undoubtfully ........... and , then you will find no options more for changing another directory .................. inconvient that I can just say , only string "C:\" printed on window .......... no button ......... no touchable controls ............................

then you can just hurt your dear disk again for uninstall ......... install again ............... disapper sometime unpredictable time ................. disturbed by this , just uninstall .......... install again ............... disapper sometime unpredictable time ................. disturbed by this , just uninstall .......... install again ............... disapper sometime unpredictable time ................. disturbed by this , just uninstall ..........

emm ............. I also think it's Shameless and moral corruption by wasting time here just lie and tease ......... all things true and true ............ but as someone who take a graduate student for only two months but still using mentality collapse as an excuse for chronic suicide , this might be also one little blocking stone on one's explore way ....................

so , sorry again ........... I tend to study in cyber-security but not professional enough to strongly clearify what's the real problem , It still angers me sometime and , can only "laugh" ....................... well ......................

**Comment by hujiujiu** [comment]
> > Thank you for the insightful feedback. How should we make omnibus more ridiculous?
> 
> sorry for making you feeel bad that ................... I meant to justify why msf-latest downloaded but never setup correctly , exactly said the biggest problem belongs to mine , for I'm controlled by someone's trojan and once i install msf , it must disapper in ten seconds (indeed shorter) even keeping origin settings , yes , don't be amazed , I paid sometime on figure out how long It shall gone .............
> 
> but ......... so said that after I tryout finding and remove everything of that virus .......... msf still seems hate my computer ..........
> 
> even if next time I gussessd that msf has gone after some wrong console-cmd reply .......... open that installer *.msi , he just shown that msf is still there and belive in it undoubtfully ........... and , then you will find no options more for changing another directory .................. inconvient that I can just say , only string "C:" printed on window .......... no button ......... no touchable controls ............................
> 
> then you can just hurt your dear disk again for uninstall ......... install again ............... disapper sometime unpredictable time ................. disturbed by this , just uninstall .......... install again ............... disapper sometime unpredictable time ................. disturbed by this , just uninstall .......... install again ............... disapper sometime unpredictable time ................. disturbed by this , just uninstall ..........
> 
> emm ............. I also think it's Shameless and moral corruption by wasting time here just lie and tease ......... all things true and true ............ but as someone who take a graduate student for only two months but still using mentality collapse as an excuse for chronic suicide , this might be also one little blocking stone on one's explore way ....................
> 
> so , sorry again ........... I tend to study in cyber-security but not professional enough to strongly clearify what's the real problem , It still angers me sometime and , can only "laugh" ....................... well ......................

must clearify that I had all anti-virus even unfriendly softwares removed ............................... including win10 buildin "Defenser" ...................

**Comment by hujiujiu** [comment]
> More red?

Oh (manually type an laugh-death emojy here) god how perfectly you make an transilation of " all chinese are red idoit " hahahahahahahaha ............ as your mother I won't be so angry but just worried about how you will deal with others in future ???????

you also enjoys playing jokes on your chinese partner ???? or insulting them by calling "hey , little pink-red" hahahahaha ?????? If so then you are just the most silly idoit I had never meet on earth hahahahahaha !!!!!!!!!!!! what's wrong with them ? and where you get gurranted just know how to insulting instead of looking in them's actual mind and life ??????? do you know what's the truth and reality in each " yellow skin pig " ?????

fuck !!!!! listen here , if you really feels that all chinese are just something following someone honestly in mind to serve like slave , although I didn't ability enough , there must be someone attach an focus on you and finally , your whole family will be cruely killd ........... you must think " Oh , what this mother fucker's saying ??? " yeah ???? yes keep this until you and allayour families cut in parts in blood ........... since you prefer put an "red hat" on all chinese , you keep on , hahahahahaaha

Or , if that just a joke and your misread accused on my depression anxiety torture illness mind , I make an apologyse for you , all things won't be easy if you say something clearly evenif a joke ....
