### ISSUE TITLE
bundle install --binstubs blows up in Ubuntu 14

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-omnibus#3]
Ubuntu version: 14.04.2 LTS (x86_64, ubuntu-14.02.2-desktop-amd64.iso). Newly installed.

Just trying to follow exactly the installation instructions [here](https://github.com/rapid7/metasploit-omnibus#installation).

Commands used prior to bundle install:

1. sudo apt-get update
2. sudo apt-get install build-essential
3. sudo apt-get install ruby-1.9.1-full
4. sudo gem install bundler
5. sudo apt-get install git

Error:

```
make[1]: Leaving directory `/tmp/bundler20150515-5897-qgzcqedep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3'
make: *** [compilelib] Error 2
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
	from extconf.rb:97:in `chdir'
	from extconf.rb:97:in `run'
	from extconf.rb:104:in `<main>'


Gem files will remain installed in /tmp/bundler20150515-5897-qgzcqedep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2 for inspection.
Results logged to /tmp/bundler20150515-5897-qgzcqedep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/gem_make.out
An error occurred while installing dep-selector-libgecode (1.0.2), and Bundler
cannot continue.
Make sure that `gem install dep-selector-libgecode -v '1.0.2'` succeeds before
bundling.
```

**Comment by wchen-r7** [comment]
You know what, I missed this important phrase:

"Ensure all the required gems are installed".

**Comment by bcook-r7** [comment]
I'm not 100% sure what all default packages have to be added to get omnibus' base gems installed when starting from bare Ubuntu desktop 14.04. The travis environment seems to already have just enough available by default, as did my vagrant boxes: https://github.com/rapid7/metasploit-omnibus/blob/master/.travis.yml

**Comment by wchen-r7** [comment]
Attempting to install ```sudo gem install dep-selector-libgecode```:

```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[1]: *** [gecode/int/extensional.o] Error 4
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/var/lib/gems/1.9.1/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3'
make: *** [compilelib] Error 2
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
	from extconf.rb:97:in `chdir'
	from extconf.rb:97:in `run'
	from extconf.rb:104:in `<main>'

```

**Comment by wchen-r7** [comment]
I also did this: https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#tldr-as-msfdev

And failed.

**Comment by bcook-r7** [comment]
OK. Since you've had nothing but failure, I'll add some shell scripts to automate the build process for a bare install of Ubuntu, Fedora and Kali linux.

**Comment by bcook-r7** [comment]
Sorry, I probably had a bunch of stuff setup that I didn't realize was actually required to get the initial gem set installed with bundler. Thanks for checking it out.

**Comment by wchen-r7** [comment]
I google'd a little bit and looks like maybe I was low on memory (kind of surprising, I had 1GB). I bumped it to 2GB and now I'm waiting to see if it resolves that error.

I will try to provide the exact steps later. I've been trying a lot of stuff and I feel it doesn't actually have to be this complicated.

**Comment by bcook-r7** [comment]
Ah! Yeah, it tries to build with a lot of concurrency by default. I did a lot of my testing on an 8-core 32GB box. That probably blew up the memory requirement on the build machine.

Once we have the build finished, it should be really easy. Sorry I don't have any published builds yet.

**Comment by wchen-r7** [comment]
LOL Ah ok. I don't have a setup like that.

**Comment by wchen-r7** [comment]
OK so... there's definitely more steps involved than what's explained in Installation and Build.

**Installation**

* 2 GB of RAM
* RVM Install 2.1.6 (or I guess 1.9 still works?)
* Install git
* sudo gem install bundler
* sudo apt-get install git
* sudo gem install dep-selector-libgecode

I think that's probably all that's needed for installation. I actually did this though:

```
sudo -kS apt-get -y install \
  build-essential zlib1g zlib1g-dev \
  libxml2 libxml2-dev libxslt-dev locate \
  libreadline6-dev libcurl4-openssl-dev git-core \
  libssl-dev libyaml-dev openssl autoconf libtool \
  ncurses-dev bison curl wget xsel postgresql \
  postgresql-contrib libpq-dev \
  libapr1 libaprutil1 libsvn1 \
  libpcap-dev libsqlite3-dev
```

**Build**

* I think I did bundle install
* Required to do: git config --global user.e-mail "email"
* Required to do: git config --global user.name "name"
* rvmsudo bin/omnibus build metasploit

And then after that I tried to build again, and I got:

``
configure: WARNING: don't have both flex and bison; reverting to lex/yacc
configure: error: Your operating system's lex is insufficient to compile
 libpcap.  flex is a lex replacement that has many advantages, including
 being able to compile libpcap. 
```

And then I'm currently not sure what to do for that at this point.

**Comment by bcook-r7** [comment]
Thanks. I just installed an Ubuntu 14.04 server from scratch and went through the steps to not miss anything. The README.md is now updated with exactly what I did: https://github.com/rapid7/metasploit-omnibus

To get reasonable build times, I configured the VM with 4 CPUs and 4 GB of ram.

**Comment by bcook-r7** [comment]
I also just added the Vagrantfile I used to configure the Ubuntu VM: https://github.com/rapid7/metasploit-omnibus/blob/master/Vagrantfile

**Comment by bcook-r7** [comment]
For your current build, I think all you need to do is run 'apt-get install bison flex', then continue with 'rvmsudo bin/omnibus build metasploit'

**Comment by bcook-r7** [comment]
I tossed a release .deb file up as well: https://github.com/rapid7/metasploit-omnibus/releases/tag/20150515

**Comment by wchen-r7** [comment]
OK thanks, I will try again.

**Comment by wchen-r7** [comment]
> For your current build, I think all you need to do is run 'apt-get install bison flex', then continue with 'rvmsudo bin/omnibus build metasploit'

I did that and then I got:
https://gist.github.com/wchen-r7/99d89244130acf5ffbef

> I tossed a release .deb file up as well: https://github.com/rapid7/metasploit-omnibus/releases/tag/20150515

This works. Thanks.

**Comment by bcook-r7** [comment]
I had fixed the UUID issue last week with e7bc068f18c8f30396e0d97c8803ae9df0315d8d I believe - git pull?

**Comment by wchen-r7** [comment]
Ah ok :-( No I didn't git pull... I downloaded it as a zip file and then copied it to my Ubuntu VMs.

**Comment by bcook-r7** [comment]
I think we have this resolved now. Thanks!

**Comment by wchen-r7** [comment]
Yup, thanks!
