### ISSUE TITLE
msfdb init failing to start the database

### ISSUE THREAD

**Issue by Maktm** [rapid7/metasploit-omnibus#53]
I'm having trouble getting the [latest build of metasploit](https://windows.metasploit.com/metasploitframework-latest.msi) to run properly. After installation, I ran `msfdb init` and I got the following output:

    PS C:\Users> msfdb init
    Found a database at C:\Users\Maktm/.msf4/db, checking to see if it is started
    Starting database at C:\Users\Maktm/.msf4/db...

and it hangs on this screen indefinitely. During this time, a process 'postgres.exe' is spawned but the command remains hanging. If I run `msfconsole`, I get the following output:

    The PGconn, PGresult, and PGError constants are deprecated, and will be
    removed as of version 1.0.
    
    You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
    
    Called from C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-
    4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
    [-] Failed to connect to the database: FATAL:  role "msf" does not exist

Also, running `db_status` inside of `msfconsole` prints this stack trace:

    msf > db_status
    [-] Error while running command db_status: FATAL:  role "msf" does not exist

    Call stack:
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
    C:/metasploit-framework/embedded/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
    C:/metasploit-framework/embedded/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
    C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
    C:/metasploit-framework/embedded/framework/lib/msf/core/db_manager/connection.rb:123:in `connection_established?'
    C:/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1613:in `cmd_db_status'
    C:/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
    C:/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
    C:/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
    C:/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
    C:/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:205:in `run'
    C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
    C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
    C:/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'

**Comment by busterb** [comment]
edit c:\metasploit-framework\embedded\framework\msfdb

In the 'run_cmd' function, comment out the 'err = stderr.read' and 'out = stdout.read' calls like this:

```
def run_cmd(cmd)
  exitstatus = 0

  err = out = ""
  Open3.popen3(cmd) do |stdin, stdout, stderr, wait_thr|
    #err = stderr.read
    #out = stdout.read
    exitstatus = wait_thr.value.exitstatus
  end
```

**Comment by Maktm** [comment]
Just tested and that fixes it. Thanks.

**Comment by XSecr3t** [comment]
Hello

I have same troublem

I try setting msfdb from termux wiki but why fail?  

> Mr.XSecr3t@localhost:/data/data/com.termux/files/usr/var/lib
$ cd $HOME/metasploit-framework/config
Mr.XSecr3t@localhost:~/metasploit-framework/config
$ ls
application.rb        database.yml.travis
boot.rb               database.yml.vagrant
cucumber.yml          environment.rb
database.yml          environments
database.yml.example
Mr.XSecr3t@localhost:~/metasploit-framework/config
$ initdb $PREFIX/var/lib/postgresql
The files belonging to this database system will be owned by user "u0_a210".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /data/data/com.termux/files/usr/var/lib/postgresql ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... sysv
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

Mr.XSecr3t@localhost:~/metasploit-framework/config
$ pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start
waiting for server to start.... done
server started
Mr.XSecr3t@localhost:~/metasploit-framework/config
$ msfconsole
[-] Failed to connect to the database: FATAL:  role "msf" does not exist

> db_status
[*] postgresql selected, no connection
msf > createuser msf
[*] exec: createuser msf

createuser: could not connect to database postgres: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/data/data/com.termux/files/usr/tmp//.s.PGSQL.5432"?
msf >

Is this something wrong? 
Thank you if you reply my problems :(

**Comment by Electrons-Force** [comment]
Me too bro...... I'm facing the same problem

**Comment by bcook-r7** [comment]
When tickets are closed, please open a new one rather than commenting on existing ones. Thanks.
