### ISSUE TITLE
Failed to connect to the database: FATAL:  role "msf" does not exist mac

### ISSUE THREAD

**Issue by xxlxlx** [rapid7/metasploit-omnibus#79]
after running msfcosole i get:

Failed to connect to the database: FATAL:  role "msf" does not exist

I have tried uninstalling and reinstalling metasploit and the database but nothing is working

Using mac so editing cmd_run wont work

**Comment by busterb** [comment]
try `msfdb reinit`

**Comment by h00die** [comment]
Maybe suggesting that in the error message would be a good idea? Trends to be a fair amount of questions about db stuff where reinit is the answer. May be able to head some of these questions off

**Comment by xxlxlx** [comment]
> It might make sense for metasploit to suggest 'msfdb reinit' to the user, though because of the wide diversity of ways users might have installed, it's not necessarily going to exist. But could work within the confines of omnibus packages perhaps.

I tried that out of msfconsole and it appeared to do something, printing:
```
~ 👉 msfdb reinit
No data at /Users/jonathan/.msf4/db, doing nothing
Found database config at /Users/jonathan/.msf4/database.yml, do you want to overwrite it?: yes
Creating database at /Users/jonathan/.msf4/db
Starting database at /Users/jonathan/.msf4/db...success
Creating database users
Creating initial database schema
```
however upon running msfconsole i was greeted with the same error as before, so it didnt work

**Comment by busterb** [comment]
Hmm, I hit a similar error just now. My initial analysis is that it appears that the default Postgres install, at least on Debian, has moved from port 5432 to 5433, which is the port that this package listens on by default.

To fix it locally, I ran 'msfdb stop', 'sudo service postgresql stop`, then `msfdb start`. My database wasn't corrupt, it was simply that a different database was suddenly listening on that port. Can you verify whether you have the same thing? You can look in ~/.msf4/db/log and see what happened.

**Comment by busterb** [comment]
Another fix is to run:

`pg_lsclusters`, and see if you have a different postgresql cluster running on that port. If you do and don't need it, simply run `pg_dropcluster` with the appropriate argument.

**Comment by Electrons-Force** [comment]
Type pg_ctl -D $PREFIX/var/lib/posgresql start

**Comment by Electrons-Force** [comment]
pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start
