### ISSUE TITLE
installer shell script should always install the latest nightly build, even if the installed version is newer

### ISSUE THREAD

**Issue by monodrone** [rapid7/metasploit-omnibus#95]
The installer shell script does not have option:

`--allow-downgrades`

From man pages
> Both of the version selection mechanisms can downgrade packages and must be used with care.

`sudo apt install metasploit-framework  `

or 

`sudo apt-get install -y metasploit-framework`

```
uname -a
Linux lada 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
cat /etc/debian_version 
8.11
```

**Comment by busterb** [comment]
Are you proposing adding '--allow-downgrades' to the apt install command line?

**Comment by monodrone** [comment]
Yes, add --allow-downgrades   .

**Comment by busterb** [comment]
Hmm, that's exactly what it does now!

https://github.com/rapid7/metasploit-omnibus/blob/master/config/templates/metasploit-framework-wrappers/msfupdate.erb#L80

You may need to download a fresher copy.
