### ISSUE TITLE
msys64 appears to be bundled with the Windows installer, but is not needed

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-omnibus#97]
Just tested the latest installer on Windows 10, msfconsole/msfvenom/msfdb worked fine even after deleting c:\metasploit-framework\embedded\msys64. This might be something that is included inside of the latest rubyinstaller zip file, but is really only needed to bundle new native gems, which the .msi installer probably should assume is actually handled by the user upgrading the whole package.

This seems to add a lot more files, and around doubles the final installation size. 

898 MB (942,452,736 bytes)
31,274 Files, 1,609 Folders

**Comment by jmartin-r7** [comment]
This should now be resolved with land of #162.
