### ISSUE TITLE
windows-latest.msi is not reliably publishing

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-omnibus#98]
As of this writing, we see the following files being published at windows.metasploit.com

```
.
├── index.html
├── LATEST
├── metasploit-framework-5.0.11+20190312193250-1rapid7-1-x64.msi
├── metasploit-framework-5.0.11+20190312193250-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.11+20190313193429-1rapid7-1-x64.msi
├── metasploit-framework-5.0.11+20190313193429-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.11+20190314193219-1rapid7-1-x64.msi
├── metasploit-framework-5.0.11+20190314193219-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.12+20190315193240-1rapid7-1-x64.msi
├── metasploit-framework-5.0.12+20190315193240-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.12+20190316193233-1rapid7-1-x64.msi
├── metasploit-framework-5.0.12+20190316193233-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.12+20190317193324-1rapid7-1-x64.msi
├── metasploit-framework-5.0.12+20190317193324-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.12+20190318193336-1rapid7-1-x64.msi
├── metasploit-framework-5.0.12+20190318193336-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.12+20190319193251-1rapid7-1-x64.msi
├── metasploit-framework-5.0.12+20190319193251-1rapid7-1-x64.msi.asc
├── metasploit-framework-5.0.13+20190320193306-1rapid7-1-x64.msi.asc
└── metasploitframework-latest.msi.asc
```

the 2 latest files are actually just signatures, which seems to indicate the pruning script is using the wrong method of deleting older files from the repository. This currently breaks the ability for `msfupdate` to do the right thing, since the file it downloads is missing.

**Comment by busterb** [comment]
This was due to the CDN not updating very quickly.

**Comment by jorgeluisrdz198** [comment]
> As of this writing, we see the following files being published at windows.metasploit.com
> 
> 
> 
>  index.html
>  LATEST
>  metasploit-framework-5.0.11+20190312193250-1rapid7-1-x64.msi
>  metasploit-framework-5.0.11+20190312193250-1rapid7-1-x64.msi.asc
>  metasploit-framework-5.0.11+20190313193429-1rapid7-1-x64.msi
>  metasploit-framework-5.0.11+20190313193429-1rapid7-1-x64.msi.asc
>  metasploit-framework-5.0.11+20190314193219-1rapid7-1-x64.msi
>  metasploit-framework-5.0.11+20190314193219-1rapid7-1-x64.msi.asc
>  metasploit-framework-5.0.12+20190315193240-1rapid7-1-x64.msi
>  metasploit-framework-5.0.12+20190315193240-1rapid7-1-x64.msi.asc
> metasploit-framework-5.0.12+20190316193233-1rapid7-1-x64.msi
>  metasploit-framework-5.0.12+20190316193233-1rapid7-1-x64.msi.asc
> metasploit-framework-5.0.12+20190317193324-1rapid7-1-x64.msi
> metasploit-framework-5.0.12+20190317193324-1rapid7-1-x64.msi.asc
> metasploit-framework-5.0.12+20190318193336-1rapid7-1-x64.msi
> metasploit-framework-5.0.12+20190318193336-1rapid7-1-x64.msi.asc
> metasploit-framework-5.0.12+20190319193251-1rapid7-1-x64.msi
>  metasploit-framework-5.0.12+20190319193251-1rapid7-1-x64.msi.asc
>  metasploit-framework-5.0.13+20190320193306-1rapid7-1-x64.msi.asc
> metasploitframework-latest.msi.asc
> 
> 
> the 2 latest files are actually just signatures, which seems to indicate the pruning script is using the wrong method of deleting older files from the repository. This currently breaks the ability for msfupdate to do the right thing, since the file it downloads is missing.

**Comment by jorgeluisrdz198** [comment]
Acceso usuario

**Comment by jorgeluisrdz198** [comment]
> Acceso usuario
